/**
 * Differential suite: the TS port must reproduce red-dwarf's outputs on real
 * openData conversations. reference.json files are generated by
 * tools/reference/generate.py (red-dwarf, random_state=42) and committed.
 *
 * PCA sign convention differs between implementations, so components and
 * projections are compared up to a per-component sign flip — detected once
 * from the components, then applied consistently to all projections.
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import {
  buildRawMatrix,
  clusterableParticipantIds,
  commentStatistics,
  findBestKmeans,
  parseModeratedOutStatementIds,
  parseVotesCsv,
  runPca,
  selectConsensusStatements,
  selectParticipants,
  selectRepresentativeStatements,
  votesPerParticipant,
  zeroOutStatements,
} from "../src/index.ts";

const FIXTURES = join(dirname(fileURLToPath(import.meta.url)), "fixtures");
const CONVERSATIONS = [
  "brexit-consensus",
  "15-per-hour-seattle",
  "canadian-electoral-reform",
  "london.youth.policing",
];

function load(name: string) {
  const dir = join(FIXTURES, name);
  const votes = parseVotesCsv(readFileSync(join(dir, "votes.csv"), "utf-8"));
  const modOut = parseModeratedOutStatementIds(
    readFileSync(join(dir, "comments.csv"), "utf-8"),
  );
  const reference = JSON.parse(
    readFileSync(join(dir, "reference.json"), "utf-8"),
  );
  return { votes, modOut, reference };
}

for (const name of CONVERSATIONS) {
  describe(`differential: ${name}`, () => {
    const { votes, modOut, reference } = load(name);
    const raw = buildRawMatrix(votes);
    const filtered = zeroOutStatements(raw, modOut);
    const pca = runPca(filtered);

    it("dedupes votes identically", () => {
      expect(votes.length).toBe(reference.meta.n_votes_deduped);
    });

    it("reproduces the raw vote matrix", () => {
      expect(raw.participantIds).toEqual(reference.matrix.participant_ids);
      expect(raw.statementIds).toEqual(reference.matrix.statement_ids);
      expect(votesPerParticipant(raw)).toEqual(
        reference.matrix.votes_per_participant,
      );
      raw.statementIds.forEach((_, j) => {
        const expected = reference.matrix.column_sums[j];
        if (expected === null) return;
        let sum = 0;
        for (const row of raw.values) {
          const v = row[j]!;
          if (!Number.isNaN(v)) sum += v;
        }
        expect(sum).toBeCloseTo(expected, 9);
      });
    });

    it("reproduces the clusterable participant filter", () => {
      const clusterable = clusterableParticipantIds(raw, 7);
      const referenceClustered = Object.keys(reference.clustering.labels)
        .map(Number)
        .sort((a, b) => a - b);
      expect(clusterable).toEqual(referenceClustered);
    });

    it("reproduces PCA means", () => {
      expect(pca.mean.length).toBe(reference.pca.mean.length);
      pca.mean.forEach((m, j) => {
        expect(m).toBeCloseTo(reference.pca.mean[j], 9);
      });
    });

    it("reproduces explained variance", () => {
      pca.explainedVariance.forEach((v, c) => {
        const expected = reference.pca.explained_variance[c];
        expect(Math.abs(v - expected) / expected).toBeLessThan(1e-8);
      });
    });

    // Sign alignment: detected from components, then applied everywhere.
    const signs = [0, 1].map((c) => {
      const ours = pca.components[c as 0 | 1];
      const theirs: number[] = reference.pca.components[c];
      let dot = 0;
      ours.forEach((v, j) => (dot += v * theirs[j]!));
      return Math.sign(dot) || 1;
    }) as [number, number];

    it("reproduces principal components (up to sign)", () => {
      [0, 1].forEach((c) => {
        const ours = pca.components[c as 0 | 1];
        const theirs: number[] = reference.pca.components[c]!;
        expect(ours.length).toBe(theirs.length);
        ours.forEach((v, j) => {
          expect(v * signs[c as 0 | 1]).toBeCloseTo(theirs[j]!, 6);
        });
      });
    });

    it("reproduces scaled participant projections", () => {
      raw.participantIds.forEach((pid, i) => {
        const expected = reference.projections.participants[String(pid)];
        expect(expected).toBeDefined();
        const [x, y] = pca.participantProjections[i]!;
        expect(x * signs[0]).toBeCloseTo(expected[0], 6);
        expect(y * signs[1]).toBeCloseTo(expected[1], 6);
      });
    });

    it("reproduces scaled statement projections", () => {
      const refStatements = reference.projections.statements;
      if (!refStatements || Object.keys(refStatements).length === 0) return;
      raw.statementIds.forEach((sid, j) => {
        const expected = refStatements[String(sid)];
        if (!expected) return;
        const [x, y] = pca.statementProjections[j]!;
        expect(x * signs[0]).toBeCloseTo(expected[0], 6);
        expect(y * signs[1]).toBeCloseTo(expected[1], 6);
      });
    });

    // ——— clustering stage ———
    const clusteredIds = Object.keys(reference.clustering.labels)
      .map(Number)
      .sort((a, b) => a - b);
    const pIndex = new Map(raw.participantIds.map((id, i) => [id, i]));
    // Cluster on projections in the reference's sign orientation, so the
    // deterministic "polis" init sees the same lexicographic row order.
    const clusterRows = clusteredIds.map((pid) => {
      const [x, y] = pca.participantProjections[pIndex.get(pid)!]!;
      return [x * signs[0], y * signs[1]];
    });

    it("reproduces k selection and exact cluster labels", () => {
      const { best } = findBestKmeans(clusterRows, 2, 5);
      expect(best.k).toBe(reference.clustering.k);
      clusteredIds.forEach((pid, i) => {
        expect(best.labels[i]).toBe(reference.clustering.labels[String(pid)]);
      });
    });

    // ——— statistics stage (isolated: reference labels as input) ———
    const referenceLabels = clusteredIds.map(
      (pid) => reference.clustering.labels[String(pid)] as number,
    );
    const clusterableRaw = selectParticipants(raw, clusteredIds);
    const stats = commentStatistics(clusterableRaw, referenceLabels);

    it("reproduces group-aware consensus", () => {
      const refAgree = reference.group_aware_consensus.agree ?? {};
      for (const [sid, expected] of Object.entries(refAgree)) {
        const actual = stats.groupAwareConsensusAgree.get(Number(sid));
        expect(actual).toBeDefined();
        expect(actual!).toBeCloseTo(expected as number, 9);
      }
    });

    it("reproduces representative statements (repness)", () => {
      const repness = selectRepresentativeStatements(stats.grouped, modOut);
      const groups = Object.keys(reference.repness);
      expect(Object.keys(repness).map(String).sort()).toEqual(groups.sort());
      for (const gid of groups) {
        const ours = repness[Number(gid)]!;
        const theirs = reference.repness[gid];
        expect(ours.map((s) => s.tid)).toEqual(theirs.map((s: any) => s.tid));
        ours.forEach((s, i) => {
          const t = theirs[i];
          expect(s["n-success"]).toBe(t["n-success"]);
          expect(s["n-trials"]).toBe(t["n-trials"]);
          expect(s["p-success"]).toBeCloseTo(t["p-success"], 9);
          expect(s["p-test"]).toBeCloseTo(t["p-test"], 9);
          if (t.repness !== undefined) {
            expect(s.repness!).toBeCloseTo(t.repness, 9);
            expect(s["repness-test"]!).toBeCloseTo(t["repness-test"], 9);
            expect(s["repful-for"]).toBe(t["repful-for"]);
          }
          if (t["best-agree"] !== undefined) {
            expect(s["best-agree"]).toBe(t["best-agree"]);
          }
        });
      }
    });

    it("reproduces overall consensus statements", () => {
      const consensus = selectConsensusStatements(raw, modOut);
      for (const direction of ["agree", "disagree"] as const) {
        const ours = consensus[direction];
        const theirs = reference.consensus[direction];
        expect(ours.map((s) => s.tid)).toEqual(theirs.map((s: any) => s.tid));
        ours.forEach((s, i) => {
          const t = theirs[i];
          expect(s["n-success"]).toBe(t["n-success"]);
          expect(s["n-trials"]).toBe(t["n-trials"]);
          expect(s["p-success"]).toBeCloseTo(t["p-success"], 9);
          expect(s["p-test"]).toBeCloseTo(t["p-test"], 9);
        });
      }
    });
  });
}
